const ACTIONS = {
    REQUEST: 'REQUEST',
    ERROR: 'ERROR',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    ADD_MOVIE_SUCCESS: 'ADD_MOVIE_SUCCESS',
    UPDATE_MOVIE_SUCCESS: 'UPDATE_MOVIE_SUCCESS',
    REMOVE_MOVIE_SUCCESS: 'REMOVE_MOVIE_SUCCESS',
};

export default ACTIONS;
